# Generated by Django 4.2.8 on 2026-04-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_normalize_legacy_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionlinesalary',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productionlinesalary',
            name='production_line',
        ),
        migrations.DeleteModel(
            name='DailyProductionRecord',
        ),
        migrations.DeleteModel(
            name='ProductionLine',
        ),
        migrations.DeleteModel(
            name='ProductionLineSalary',
        ),
    ]
