# Generated by Django 4.2.8 on 2026-04-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_document_extracted_text_document_type_clientpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='Structured data parsed from a Client PI document (client name, items, deadline, etc.).'),
        ),
    ]
