# Generated by Django 4.2.8 on 2026-04-18 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_add_document_structured_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='supplier_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_address', models.TextField(blank=True)),
                ('items', models.JSONField(default=list)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent to Supplier'), ('FULFILLED', 'Fulfilled')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('proforma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='logistics.proformainvoice')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='logistics.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
