# Generated by Django 4.2.8 on 2026-04-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_proformainvoice_supplier_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='min_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum quantity accepted per order.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='reference_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Typical unit price used for quick comparison.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplies',
            field=models.TextField(blank=True, help_text='Products or materials this supplier can provide.'),
        ),
    ]
