# Generated by Django 4.2.8 on 2026-04-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0018_supplierproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='resale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suggested client-facing resale price per unit.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='specifications',
            field=models.TextField(blank=True, help_text='Technical details, grade, size, material, etc.'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='min_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum quantity the supplier will accept per order.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Supplier's quoted buying/cost price per unit.", max_digits=12, null=True),
        ),
    ]
