# Generated by Django 4.2.8 on 2026-04-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0019_supplierproduct_resale_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-issued_at'], 'permissions': (('can_reverse_receipts', 'Can reverse or refund receipts'),)},
        ),
        migrations.AddField(
            model_name='transactionpaymentrecord',
            name='amount_due_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transactionpaymentrecord',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transactionpaymentrecord',
            name='cash_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='transactionpaymentrecord',
            name='change_given',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transactionpaymentrecord',
            name='is_full_payment',
            field=models.BooleanField(default=False),
        ),
    ]
