# Generated by Django 4.2.8 on 2026-04-18 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0020_alter_receipt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Owner transaction for this stored stock item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='logistics.transaction'),
        ),
    ]
