# Generated by Django 4.2.8 on 2026-04-20 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0021_inventoryitem_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='final_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='logistics.finalinvoice'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='parent_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='split_purchase_orders', to='logistics.purchaseorder'),
        ),
    ]
