# Generated by Django 4.2.7 on 2026-04-21 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0025_invoice_quote_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAREHOUSE_RECEIVED', 'Received In Warehouse'), ('ALLOCATED', 'Allocated For Shipment'), ('DISPATCHED_FROM_WAREHOUSE', 'Dispatched From Warehouse'), ('AT_PORT', 'At Port Of Loading'), ('SEA_TRANSIT', 'Sea Transit'), ('AT_DESTINATION_PORT', 'Arrived At Destination Port'), ('INLAND_TRANSIT', 'Inland Transit'), ('DELIVERED', 'Delivered')], default='WAREHOUSE_RECEIVED', max_length=32)),
                ('warehouse_received_at', models.DateTimeField(blank=True, null=True)),
                ('warehouse_notes', models.TextField(blank=True)),
                ('port_of_loading', models.CharField(blank=True, max_length=255)),
                ('destination_port', models.CharField(blank=True, max_length=255)),
                ('inland_destination', models.CharField(blank=True, max_length=255)),
                ('consignee', models.CharField(blank=True, max_length=255)),
                ('planned_dispatch_date', models.DateField(blank=True, null=True)),
                ('planned_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_fulfillment_orders', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_order', to='logistics.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FulfillmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_allocated', models.PositiveIntegerField(default=0)),
                ('quantity_dispatched', models.PositiveIntegerField(default=0)),
                ('quantity_delivered', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_lines', to='logistics.inventoryitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='logistics.fulfillmentorder')),
            ],
            options={
                'ordering': ['inventory_item__item_name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('leg_type', models.CharField(choices=[('WAREHOUSE_TO_PORT', 'Warehouse To Port'), ('SEA_FREIGHT', 'Sea Freight'), ('PORT_TO_DESTINATION', 'Port To Destination')], max_length=24)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('carrier', models.CharField(blank=True, max_length=255)),
                ('vehicle_or_vessel', models.CharField(blank=True, max_length=255)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('arrival_eta', models.DateField(blank=True, null=True)),
                ('actual_arrival', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed')], default='PLANNED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shipment_legs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='logistics.fulfillmentorder')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
                'unique_together': {('order', 'sequence')},
            },
        ),
    ]
