# Generated by Django 4.2.7 on 2026-04-21 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0026_fulfillmentorder_fulfillmentline_shipmentleg'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillmentorder',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_orders', to='logistics.purchaseorder'),
        ),
        migrations.AddField(
            model_name='fulfillmentorder',
            name='source_type',
            field=models.CharField(choices=[('PURCHASE_ORDER', 'Purchase Order'), ('WAREHOUSE', 'Warehouse Stock')], default='PURCHASE_ORDER', max_length=20),
        ),
    ]
