# Generated by Django 4.2.7 on 2026-04-21 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0027_fulfillmentorder_purchase_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulfillmentorder',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='fulfillmentorder',
            name='source_type',
        ),
        migrations.AddField(
            model_name='fulfillmentorder',
            name='final_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_orders', to='logistics.finalinvoice'),
        ),
        migrations.AddField(
            model_name='fulfillmentorder',
            name='requires_warehouse_handling',
            field=models.BooleanField(default=False),
        ),
    ]
