# Generated by Django 4.2.7 on 2026-04-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0028_remove_fulfillmentorder_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loading',
            name='bill_of_lading_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loading',
            name='entry_type',
            field=models.CharField(choices=[('FULL_CONTAINER', 'Full Container'), ('GROUPAGE', 'Groupage')], default='FULL_CONTAINER', max_length=20),
        ),
        migrations.AddField(
            model_name='loading',
            name='warehouse_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Entry Number'),
        ),
    ]
