# Generated by Django 4.2.7 on 2026-04-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0029_loading_bill_of_lading_number_loading_entry_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loading',
            name='groupage_note_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='loading',
            name='container_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
