# Generated by Django 4.2.7 on 2026-04-26 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0030_loading_groupage_note_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('LCL_FREIGHT', 'LCL Freight'), ('HANDLING', 'Handling'), ('STORAGE', 'Storage'), ('FCL_FLAT', 'FCL Flat'), ('PORT', 'Port'), ('TRANSPORT', 'Transport'), ('DEMURRAGE', 'Demurrage'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('trigger_event', models.CharField(max_length=64)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVOICED', 'Invoiced'), ('VOID', 'Void')], default='OPEN', max_length=12)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('VOID', 'Void')], default='DRAFT', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_billing_invoices', to='logistics.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CargoItemWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('description', models.TextField()),
                ('package_count', models.PositiveIntegerField(default=1)),
                ('quantity_total', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('quantity_delivered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('volumetric_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('chargeable_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('VERIFIED', 'Verified'), ('ALLOCATED', 'Allocated'), ('LOADED', 'Loaded'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('PARTIALLY_DELIVERED', 'Partially Delivered'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=24)),
                ('inventory_state', models.CharField(choices=[('WAREHOUSE', 'Warehouse Stock'), ('RESERVED', 'Reserved'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], default='WAREHOUSE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workflow_cargo_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['shipment', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_type', models.CharField(max_length=40)),
                ('aggregate_id', models.CharField(max_length=64)),
                ('event_type', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_domain_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('SHIPMENT', 'Shipment'), ('CARGO', 'Cargo')], max_length=16)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_transition_logs', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transition_logs', to='logistics.domainevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('mode', models.CharField(choices=[('FCL', 'Full Container Load'), ('LCL', 'Groupage (LCL)')], max_length=3)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('VERIFIED', 'Verified'), ('ALLOCATED', 'Allocated'), ('LOADED', 'Loaded'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=20)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('warehouse_location', models.CharField(max_length=255)),
                ('lcl_rate_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fcl_flat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('handling_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('storage_fee_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_shipments', to='logistics.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workflow_shipments', to=settings.AUTH_USER_MODEL)),
                ('loading', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_shipment', to='logistics.loading')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_warehouse', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qty_reserved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qty_in_transit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qty_delivered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('version', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_position', to='logistics.cargoitemworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RECEIVED', 'Received'), ('RESERVED', 'Reserved'), ('RELEASED', 'Released'), ('LOADED', 'Loaded'), ('DELIVERED', 'Delivered'), ('ADJUSTMENT', 'Adjustment')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('from_state', models.CharField(blank=True, max_length=20)),
                ('to_state', models.CharField(blank=True, max_length=20)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cargo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='logistics.cargoitemworkflow')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='logistics.domainevent')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='logistics.inventoryposition')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='logistics.shipmentworkflow')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='cargoitemworkflow',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_items', to='logistics.shipmentworkflow'),
        ),
        migrations.CreateModel(
            name='BillingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Cheque')], default='CASH', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_workflow_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='logistics.billinginvoice')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('charge', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line', to='logistics.billingcharge')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='logistics.billinginvoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_invoices', to='logistics.shipmentworkflow'),
        ),
        migrations.AddField(
            model_name='billingcharge',
            name='cargo_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_charges', to='logistics.cargoitemworkflow'),
        ),
        migrations.AddField(
            model_name='billingcharge',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_charges', to='logistics.domainevent'),
        ),
        migrations.AddField(
            model_name='billingcharge',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_charges', to='logistics.shipmentworkflow'),
        ),
        migrations.AddConstraint(
            model_name='inventoryposition',
            constraint=models.CheckConstraint(check=models.Q(('qty_warehouse__gte', 0), ('qty_reserved__gte', 0), ('qty_in_transit__gte', 0), ('qty_delivered__gte', 0)), name='inventory_position_non_negative_balances'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='inventory_movement_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='cargoitemworkflow',
            constraint=models.CheckConstraint(check=models.Q(('quantity_total__gt', 0)), name='workflow_cargo_quantity_total_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='cargoitemworkflow',
            constraint=models.CheckConstraint(check=models.Q(('quantity_delivered__gte', 0)), name='workflow_cargo_quantity_delivered_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='cargoitemworkflow',
            constraint=models.CheckConstraint(check=models.Q(('quantity_delivered__lte', models.F('quantity_total'))), name='workflow_cargo_quantity_delivered_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='billingpayment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='billing_payment_amount_gt_zero'),
        ),
    ]
