# Generated by Django 4.2.7 on 2026-04-28 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0036_transaction_source_loading_invoice_loading_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('USD', 'USD - US Dollar'), ('UGX', 'UGX - Ugandan Shilling'), ('CNY', 'CNY - Chinese Yuan'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('KES', 'KES - Kenyan Shilling')], default='USD', max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='logistics.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
