# Generated by Django 4.2.7 on 2026-04-29 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0037_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_by_name', models.CharField(help_text='Name of the person who physically received the goods.', max_length=255)),
                ('received_by_phone', models.CharField(blank=True, max_length=40)),
                ('delivery_address', models.CharField(blank=True, help_text='Free-text place name (warehouse, office, site, etc.).', max_length=255)),
                ('signature_or_photo', models.FileField(blank=True, help_text='Photo of the signed delivery note, ID, or signature image.', null=True, upload_to='pod/')),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proofs_of_delivery', to=settings.AUTH_USER_MODEL)),
                ('fulfillment_order', models.OneToOneField(blank=True, help_text='Set when the POD closes a sourcing / trading delivery.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proof_of_delivery', to='logistics.fulfillmentorder')),
                ('loading', models.OneToOneField(blank=True, help_text='Set when the POD closes a logistics shipment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proof_of_delivery', to='logistics.loading')),
            ],
            options={
                'verbose_name': 'Proof of Delivery',
                'verbose_name_plural': 'Proofs of Delivery',
                'ordering': ['-delivered_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='proofofdelivery',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('fulfillment_order__isnull', True), ('loading__isnull', False)), models.Q(('fulfillment_order__isnull', False), ('loading__isnull', True)), _connector='OR'), name='pod_belongs_to_exactly_one_workflow'),
        ),
    ]
