# Generated by Django 4.2.7 on 2026-04-29 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0038_proof_of_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='loading',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loading',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_loadings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loading',
            name='closure_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='closure_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('CLEANED', 'Cleaned'), ('SENT_TO_SOURCING', 'Sent To Sourcing'), ('QUOTED', 'Quoted'), ('PROFORMA_CREATED', 'Proforma Created'), ('PROFORMA_SENT', 'Proforma Sent'), ('CONFIRMED', 'Confirmed'), ('FINAL_INVOICE_CREATED', 'Final Invoice Created'), ('PAID', 'Paid'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CLOSED', 'Closed')], default='RECEIVED', max_length=30),
        ),
    ]
