# Generated by Django 4.2.7 on 2026-05-03 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('logistics', '0040_supplierpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.FileField(blank=True, null=True, upload_to='signatures/')),
                ('title', models.CharField(default='Authorized Signatory', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signature Profile',
                'verbose_name_plural': 'Signature Profiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('signer_name', models.CharField(max_length=150)),
                ('signer_title', models.CharField(max_length=120)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('signature_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_signatures', to='logistics.signatureprofile')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Signature',
                'verbose_name_plural': 'Document Signatures',
                'ordering': ['-signed_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentsignature',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='one_signature_per_business_document'),
        ),
    ]
