# Generated by Django 4.2.7 on 2026-05-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0041_signatureprofile_documentsignature_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='logistics_a_timesta_ad09de_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_type', 'action', '-timestamp'], name='logistics_a_model_t_c65cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='logistics_a_user_id_3cf5bf_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='logistics_c_name_76b629_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone'], name='logistics_c_phone_0a3935_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['-created_at'], name='logistics_c_created_481648_idx'),
        ),
        migrations.AddIndex(
            model_name='loading',
            index=models.Index(fields=['entry_type', 'closed_at'], name='logistics_l_entry_t_4ccd42_idx'),
        ),
        migrations.AddIndex(
            model_name='loading',
            index=models.Index(fields=['client', '-created_at'], name='logistics_l_client__362edd_idx'),
        ),
        migrations.AddIndex(
            model_name='loading',
            index=models.Index(fields=['origin'], name='logistics_l_origin_ef850a_idx'),
        ),
        migrations.AddIndex(
            model_name='loading',
            index=models.Index(fields=['-created_at'], name='logistics_l_created_b78aac_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='logistics_n_recipie_3619e6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['category', '-created_at'], name='logistics_n_categor_69890b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'closed_at'], name='logistics_t_status_ed2133_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer', '-created_at'], name='logistics_t_custome_3dad3d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['source_loading'], name='logistics_t_source__2a3e66_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created_at'], name='logistics_t_created_7a0d43_idx'),
        ),
    ]
