# Generated by Django 4.2.7 on 2026-05-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0044_proformainvoice_source_sourcing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingpayment',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='payments/proofs/billing/'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='payments/proofs/logistics/'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='payments/proofs/suppliers/'),
        ),
        migrations.AddField(
            model_name='transactionpaymentrecord',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='payments/proofs/trade/'),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='reference',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='reference',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='reference',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='transactionpaymentrecord',
            name='reference',
            field=models.CharField(max_length=100),
        ),
    ]
