# Generated by Django 4.2.7 on 2026-05-15 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0045_billingpayment_proof_of_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeboardTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('assigned_role', models.CharField(blank=True, choices=[('ADMIN', 'System Admin'), ('DIRECTOR', 'Director'), ('OFFICE_ADMIN', 'Office Admin (Uganda Intake)'), ('FINANCE', 'Finance Officer'), ('PROCUREMENT', 'Procurement Officer')], max_length=20)),
                ('is_done', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_noticeboard_tasks', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_noticeboard_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_noticeboard_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_done', '-created_at'],
                'indexes': [models.Index(fields=['is_done', '-created_at'], name='logistics_n_is_done_8d6135_idx'), models.Index(fields=['assigned_role', 'is_done'], name='logistics_n_assigne_7b055a_idx')],
            },
        ),
    ]
