# Generated by GitHub Copilot on 2026-05-18

from django.db import migrations, models
import django.db.models.deletion


def link_existing_final_invoices(apps, schema_editor):
    FinalInvoice = apps.get_model("logistics", "FinalInvoice")
    ProformaInvoice = apps.get_model("logistics", "ProformaInvoice")

    for proforma in ProformaInvoice.objects.order_by("created_at", "pk"):
        invoices = FinalInvoice.objects.filter(
            transaction_id=proforma.transaction_id,
            proforma__isnull=True,
        )
        if proforma.loading_id:
            invoices = invoices.filter(loading_id=proforma.loading_id)
        invoice = invoices.order_by("created_at", "pk").first()
        if invoice:
            invoice.proforma_id = proforma.pk
            invoice.save(update_fields=["proforma"])


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0046_noticeboardtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalinvoice",
            name="proforma",
            field=models.OneToOneField(
                blank=True,
                help_text="The single proforma this final invoice was generated from.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="final_invoice",
                to="logistics.proformainvoice",
            ),
        ),
        migrations.RunPython(link_existing_final_invoices, migrations.RunPython.noop),
    ]
