# Generated by GitHub Copilot on 2026-05-31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0050_documentarchive_payment_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralQuotation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("purpose", models.CharField(choices=[("SERVICE", "Service"), ("CONSULTATION", "Consultation"), ("CLEARING", "Clearing"), ("SHIPPING", "Shipping"), ("STORAGE", "Storage"), ("DOCUMENTATION", "Documentation"), ("ADJUSTMENT", "Adjustment"), ("OTHER", "Other")], default="SERVICE", max_length=20)),
                ("custom_purpose", models.CharField(blank=True, max_length=255)),
                ("items", models.JSONField(blank=True, default=list)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("notes", models.TextField(blank=True)),
                ("terms", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quotation_number", models.CharField(editable=False, max_length=32, unique=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SENT", "Sent"), ("ACCEPTED", "Accepted"), ("CONVERTED", "Converted"), ("VOID", "Void")], default="DRAFT", max_length=12)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="generalquotations", to="logistics.client")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_generalquotations", to=settings.AUTH_USER_MODEL)),
                ("transaction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="generalquotations", to="logistics.transaction")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="GeneralInvoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("purpose", models.CharField(choices=[("SERVICE", "Service"), ("CONSULTATION", "Consultation"), ("CLEARING", "Clearing"), ("SHIPPING", "Shipping"), ("STORAGE", "Storage"), ("DOCUMENTATION", "Documentation"), ("ADJUSTMENT", "Adjustment"), ("OTHER", "Other")], default="SERVICE", max_length=20)),
                ("custom_purpose", models.CharField(blank=True, max_length=255)),
                ("items", models.JSONField(blank=True, default=list)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("notes", models.TextField(blank=True)),
                ("terms", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_number", models.CharField(editable=False, max_length=32, unique=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("ISSUED", "Issued"), ("PARTIALLY_PAID", "Partially Paid"), ("PAID", "Paid"), ("VOID", "Void")], default="DRAFT", max_length=20)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("amount_paid", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("balance", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="generalinvoices", to="logistics.client")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_generalinvoices", to=settings.AUTH_USER_MODEL)),
                ("quotation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="general_invoices", to="logistics.generalquotation")),
                ("transaction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="generalinvoices", to="logistics.transaction")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="GeneralPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("method", models.CharField(choices=[("CASH", "Cash"), ("BANK_TRANSFER", "Bank Transfer"), ("MOBILE_MONEY", "Mobile Money"), ("CHEQUE", "Cheque"), ("OTHER", "Other")], default="CASH", max_length=20)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("proof_of_payment", models.FileField(blank=True, null=True, upload_to="payments/proofs/general/")),
                ("paid_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="general_payments", to=settings.AUTH_USER_MODEL)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="logistics.generalinvoice")),
            ],
            options={"ordering": ["-paid_at", "-id"]},
        ),
        migrations.CreateModel(
            name="GeneralReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("receipt_number", models.CharField(editable=False, max_length=32, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("issued_to", models.CharField(max_length=255)),
                ("purpose", models.CharField(blank=True, max_length=255)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("payment", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="receipt", to="logistics.generalpayment")),
            ],
            options={"ordering": ["-issued_at"]},
        ),
    ]
